version: '3.9'
services:
  front:
    platform: linux/amd64
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./front:/app
  api:
    platform: linux/amd64
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app
